In [1]:
from ucimlrepo import fetch_ucirepo, list_available_datasets

import pprint

In [2]:
# Fetch the dataset from OpenML
chronic_kidney_disease = fetch_ucirepo(id=336)
pprint.pp(chronic_kidney_disease.metadata)

{'uci_id': 336,
 'name': 'Chronic Kidney Disease',
 'repository_url': 'https://archive.ics.uci.edu/dataset/336/chronic+kidney+disease',
 'data_url': 'https://archive.ics.uci.edu/static/public/336/data.csv',
 'abstract': 'This dataset can be used to predict the chronic kidney disease '
             'and it can be collected from the hospital nearly 2 months of '
             'period.',
 'area': 'Other',
 'tasks': ['Classification'],
 'characteristics': ['Multivariate'],
 'num_instances': 400,
 'num_features': 24,
 'feature_types': ['Real'],
 'demographics': ['Age'],
 'target_col': ['class'],
 'index_col': None,
 'has_missing_values': 'yes',
 'missing_values_symbol': 'NaN',
 'year_of_dataset_creation': 2015,
 'last_updated': 'Mon Mar 04 2024',
 'dataset_doi': '10.24432/C5G020',
 'creators': ['L. Rubini', 'P. Soundarapandian', 'P. Eswaran'],
 'intro_paper': None,
 'additional_info': {'summary': 'We use the following representation to '
                                'collect the dataset\r\n'
                                '                        age\t\t-\tage\t\r\n'
                                '\t\t\tbp\t\t-\tblood pressure\r\n'
                                '\t\t\tsg\t\t-\tspecific gravity\r\n'
                                '\t\t\tal\t\t-   \talbumin\r\n'
                                '\t\t\tsu\t\t-\tsugar\r\n'
                                '\t\t\trbc\t\t-\tred blood cells\r\n'
                                '\t\t\tpc\t\t-\tpus cell\r\n'
                                '\t\t\tpcc\t\t-\tpus cell clumps\r\n'
                                '\t\t\tba\t\t-\tbacteria\r\n'
                                '\t\t\tbgr\t\t-\tblood glucose random\r\n'
                                '\t\t\tbu\t\t-\tblood urea\r\n'
                                '\t\t\tsc\t\t-\tserum creatinine\r\n'
                                '\t\t\tsod\t\t-\tsodium\r\n'
                                '\t\t\tpot\t\t-\tpotassium\r\n'
                                '\t\t\themo\t\t-\themoglobin\r\n'
                                '\t\t\tpcv\t\t-\tpacked cell volume\r\n'
                                '\t\t\twc\t\t-\twhite blood cell count\r\n'
                                '\t\t\trc\t\t-\tred blood cell count\r\n'
                                '\t\t\thtn\t\t-\thypertension\r\n'
                                '\t\t\tdm\t\t-\tdiabetes mellitus\r\n'
                                '\t\t\tcad\t\t-\tcoronary artery disease\r\n'
                                '\t\t\tappet\t\t-\tappetite\r\n'
                                '\t\t\tpe\t\t-\tpedal edema\r\n'
                                '\t\t\tane\t\t-\tanemia\r\n'
                                '\t\t\tclass\t\t-\tclass\t',
                     'purpose': None,
                     'funded_by': None,
                     'instances_represent': None,
                     'recommended_data_splits': None,
                     'sensitive_data': None,
                     'preprocessing_description': None,
                     'variable_info': 'We use 24 + class = 25 ( 11  numeric '
                                      ',14  nominal)\r\n'
                                      '1.Age(numerical)\r\n'
                                      '  \t  \tage in years\r\n'
                                      ' \t2.Blood Pressure(numerical)\r\n'
                                      '\t       \tbp in mm/Hg\r\n'
                                      ' \t3.Specific Gravity(nominal)\r\n'
                                      '\t  \tsg - '
                                      '(1.005,1.010,1.015,1.020,1.025)\r\n'
                                      ' \t4.Albumin(nominal)\r\n'
                                      '\t\tal - (0,1,2,3,4,5)\r\n'
                                      ' \t5.Sugar(nominal)\r\n'
                                      '\t\tsu - (0,1,2,3,4,5)\r\n'
                                      ' \t6.Red Blood Cells(nominal)\r\n'
                                      '\t\trbc - (normal,abnormal)\r\n'
                                      ' \t7.Pus Cell (nominal)\r\n'
                                      '\t\tpc - (normal,abnormal)\r\n'
                                      ' \t8.Pus Cell clumps(nominal)\r\n'
                                      '\t\tpcc - (present,notpresent)\r\n'
                                      ' \t9.Bacteria(nominal)\r\n'
                                      '\t\tba  - (present,notpresent)\r\n'
                                      ' \t10.Blood Glucose '
                                      'Random(numerical)\t\t\r\n'
                                      '\t\tbgr in mgs/dl\r\n'
                                      ' \t11.Blood Urea(numerical)\t\r\n'
                                      '\t\tbu in mgs/dl\r\n'
                                      ' \t12.Serum Creatinine(numerical)\t\r\n'
                                      '\t\tsc in mgs/dl\r\n'
                                      ' \t13.Sodium(numerical)\r\n'
                                      '\t\tsod in mEq/L\r\n'
                                      ' \t14.Potassium(numerical)\t\r\n'
                                      '\t\tpot in mEq/L\r\n'
                                      ' \t15.Hemoglobin(numerical)\r\n'
                                      '\t\themo in gms\r\n'
                                      ' \t16.Packed  Cell Volume(numerical)\r\n'
                                      ' \t17.White Blood Cell '
                                      'Count(numerical)\r\n'
                                      '\t\twc in cells/cumm\r\n'
                                      ' \t18.Red Blood Cell '
                                      'Count(numerical)\t\r\n'
                                      '\t\trc in millions/cmm\r\n'
                                      ' \t19.Hypertension(nominal)\t\r\n'
                                      '\t\thtn - (yes,no)\r\n'
                                      ' \t20.Diabetes Mellitus(nominal)\t\r\n'
                                      '\t\tdm - (yes,no)\r\n'
                                      ' \t21.Coronary Artery '
                                      'Disease(nominal)\r\n'
                                      '\t\tcad - (yes,no)\r\n'
                                      ' \t22.Appetite(nominal)\t\r\n'
                                      '\t\tappet - (good,poor)\r\n'
                                      ' \t23.Pedal Edema(nominal)\r\n'
                                      '\t\tpe - (yes,no)\t\r\n'
                                      ' \t24.Anemia(nominal)\r\n'
                                      '\t\tane - (yes,no)\r\n'
                                      ' \t25.Class (nominal)\t\t\r\n'
                                      '\t\tclass - (ckd,notckd)',
                     'citation': None}}

In [3]:
chronic_kidney_disease.metadata.target_col

['class']

In [4]:
chronic_kidney_disease.data.features

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,hemo,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,15.4,44.0,7800.0,5.2,yes,yes,no,good,no,no
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,11.3,38.0,6000.0,NaN,no,no,no,good,no,no
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,9.6,31.0,7500.0,NaN,no,yes,no,poor,no,yes
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,11.2,32.0,6700.0,3.9,yes,no,no,poor,yes,yes
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,11.6,35.0,7300.0,4.6,no,no,no,good,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,140.0,...,15.7,47.0,6700.0,4.9,no,no,no,good,no,no
396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,...,16.5,54.0,7800.0,6.2,no,no,no,good,no,no
397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,15.8,49.0,6600.0,5.4,no,no,no,good,no,no
398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,114.0,...,14.2,51.0,7200.0,5.9,no,no,no,good,no,no
399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,...,15.8,53.0,6800.0,6.1,no,no,no,good,no,no

In [5]:
chronic_kidney_disease.data.targets

      class
0       ckd
1       ckd
2       ckd
3       ckd
4       ckd
..      ...
395  notckd
396  notckd
397  notckd
398  notckd
399  notckd

[400 rows x 1 columns]

In [6]:
chronic_kidney_disease.data.original

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane,class
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44.0,7800.0,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38.0,6000.0,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31.0,7500.0,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35.0,7300.0,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,140.0,...,47.0,6700.0,4.9,no,no,no,good,no,no,notckd
396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,...,54.0,7800.0,6.2,no,no,no,good,no,no,notckd
397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,49.0,6600.0,5.4,no,no,no,good,no,no,notckd
398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,114.0,...,51.0,7200.0,5.9,no,no,no,good,no,no,notckd
399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,...,53.0,6800.0,6.1,no,no,no,good,no,no,notckd

In [7]:
chronic_kidney_disease.variables

,name,role,type,demographic,description,units,missing_values
0,age,Feature,Integer,Age,None,year,yes
1,bp,Feature,Integer,None,blood pressure,mm/Hg,yes
2,sg,Feature,Categorical,None,specific gravity,None,yes
3,al,Feature,Categorical,None,albumin,None,yes
4,su,Feature,Categorical,None,sugar,None,yes
5,rbc,Feature,Binary,None,red blood cells,None,yes
6,pc,Feature,Binary,None,pus cell,None,yes
7,pcc,Feature,Binary,None,pus cell clumps,None,yes
8,ba,Feature,Binary,None,bacteria,None,yes
9,bgr,Feature,Integer,None,blood glucose random,mgs/dl,yes
10,bu,Feature,Integer,None,blood urea,mgs/dl,yes
11,sc,Feature,Continuous,None,serum creatinine,mgs/dl,yes
12,sod,Feature,Integer,None,sodium,mEq/L,yes
13,pot,Feature,Continuous,None,potassium,mEq/L,yes
14,hemo,Feature,Continuous,None,hemoglobin,gms,yes
15,pcv,Feature,Integer,None,packed cell volume,None,yes
16,wbcc,Feature,Integer,None,white blood cell count,cells/cmm,yes
17,rbcc,Feature,Continuous,None,red blood cell count,millions/cmm,yes
18,htn,Feature,Binary,None,hypertension,None,yes
19,dm,Feature,Binary,None,diabetes mellitus,None,yes
20,cad,Feature,Binary,None,coronary artery disease,None,yes
21,appet,Feature,Binary,None,appetite,None,yes
22,pe,Feature,Binary,None,pedal edema,None,yes
23,ane,Feature,Binary,None,anemia,None,yes
24,class,Target,Binary,None,ckd or not ckd,None,no

In [8]:
# Print all the keys in the chronic_kidney_disease object to understand its structure
print(chronic_kidney_disease.keys())

dict_keys(['data', 'metadata', 'variables'])

In [9]:
import pandas as pd

# Extract features, targets, and headers
features = chronic_kidney_disease.data['features']
targets = chronic_kidney_disease.data['targets']
headers = chronic_kidney_disease.data['headers']

# Combine features and targets into a DataFrame
df = pd.DataFrame(features, columns=headers[:-1])  # All except last column
df['target'] = targets  # Add the target column

# Display DataFrame info
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     391 non-null    float64
 1   bp      388 non-null    float64
 2   sg      353 non-null    float64
 3   al      354 non-null    float64
 4   su      351 non-null    float64
 5   rbc     248 non-null    object
 6   pc      335 non-null    object
 7   pcc     396 non-null    object
 8   ba      396 non-null    object
 9   bgr     356 non-null    float64
 10  bu      381 non-null    float64
 11  sc      383 non-null    float64
 12  sod     313 non-null    float64
 13  pot     312 non-null    float64
 14  hemo    348 non-null    float64
 15  pcv     329 non-null    float64
 16  wbcc    294 non-null    float64
 17  rbcc    269 non-null    float64
 18  htn     398 non-null    object
 19  dm      398 non-null    object
 20  cad     398 non-null    object
 21  appet   399 non-null    object
 22  pe      399 non-null    object
 23  ane     399 non-null    object
 24  target  400 non-null    object
dtypes: float64(14), object(11)
memory usage: 78.3+ KB
None

In [10]:
# Summary statistics
print(df.describe())

# Check for missing values
print(df.isnull().sum())

              age          bp          sg          al          su         bgr  \
count  391.000000  388.000000  353.000000  354.000000  351.000000  356.000000
mean    51.483376   76.469072    1.017408    1.016949    0.450142  148.036517
std     17.169714   13.683637    0.005717    1.352679    1.099191   79.281714
min      2.000000   50.000000    1.005000    0.000000    0.000000   22.000000
25%     42.000000   70.000000    1.010000    0.000000    0.000000   99.000000
50%     55.000000   80.000000    1.020000    0.000000    0.000000  121.000000
75%     64.500000   80.000000    1.020000    2.000000    0.000000  163.000000
max     90.000000  180.000000    1.025000    5.000000    5.000000  490.000000

               bu          sc         sod         pot        hemo         pcv  \
count  381.000000  383.000000  313.000000  312.000000  348.000000  329.000000
mean    57.425722    3.072454  137.528754    4.627244   12.526437   38.884498
std     50.503006    5.741126   10.408752    3.193904    2.912587    8.990105
min      1.500000    0.400000    4.500000    2.500000    3.100000    9.000000
25%     27.000000    0.900000  135.000000    3.800000   10.300000   32.000000
50%     42.000000    1.300000  138.000000    4.400000   12.650000   40.000000
75%     66.000000    2.800000  142.000000    4.900000   15.000000   45.000000
max    391.000000   76.000000  163.000000   47.000000   17.800000   54.000000

               wbcc        rbcc
count    294.000000  269.000000
mean    8406.122449    4.707435
std     2944.474190    1.025323
min     2200.000000    2.100000
25%     6500.000000    3.900000
50%     8000.000000    4.800000
75%     9800.000000    5.400000
max    26400.000000    8.000000
age         9
bp         12
sg         47
al         46
su         49
rbc       152
pc         65
pcc         4
ba          4
bgr        44
bu         19
sc         17
sod        87
pot        88
hemo       52
pcv        71
wbcc      106
rbcc      131
htn         2
dm          2
cad         2
appet       1
pe          1
ane         1
target      0
dtype: int64

In [11]:
# variable information
print(chronic_kidney_disease.variables)

     name     role         type demographic              description  \
0     age  Feature      Integer         Age                     None
1      bp  Feature      Integer        None           blood pressure
2      sg  Feature  Categorical        None         specific gravity
3      al  Feature  Categorical        None                  albumin
4      su  Feature  Categorical        None                    sugar
5     rbc  Feature       Binary        None          red blood cells
6      pc  Feature       Binary        None                 pus cell
7     pcc  Feature       Binary        None          pus cell clumps
8      ba  Feature       Binary        None                 bacteria
9     bgr  Feature      Integer        None     blood glucose random
10     bu  Feature      Integer        None               blood urea
11     sc  Feature   Continuous        None         serum creatinine
12    sod  Feature      Integer        None                   sodium
13    pot  Feature   Continuous        None                potassium
14   hemo  Feature   Continuous        None               hemoglobin
15    pcv  Feature      Integer        None       packed cell volume
16   wbcc  Feature      Integer        None   white blood cell count
17   rbcc  Feature   Continuous        None     red blood cell count
18    htn  Feature       Binary        None             hypertension
19     dm  Feature       Binary        None        diabetes mellitus
20    cad  Feature       Binary        None  coronary artery disease
21  appet  Feature       Binary        None                 appetite
22     pe  Feature       Binary        None              pedal edema
23    ane  Feature       Binary        None                   anemia
24  class   Target       Binary        None           ckd or not ckd

           units missing_values
0           year            yes
1          mm/Hg            yes
2           None            yes
3           None            yes
4           None            yes
5           None            yes
6           None            yes
7           None            yes
8           None            yes
9         mgs/dl            yes
10        mgs/dl            yes
11        mgs/dl            yes
12         mEq/L            yes
13         mEq/L            yes
14           gms            yes
15          None            yes
16     cells/cmm            yes
17  millions/cmm            yes
18          None            yes
19          None            yes
20          None            yes
21          None            yes
22          None            yes
23          None            yes
24          None             no

## Handling Misssing Values

In [15]:
import numpy as np

# Load features and targets as pandas DataFrame
X = chronic_kidney_disease.data.features.copy()  
Y = chronic_kidney_disease.data.targets

# Replace "?" with NaN in the features DataFrame
X = X.replace("?", np.nan)  # Avoid inplace operation to bypass warning

# Combine features and target into a single DataFrame
df_combined = pd.concat([X, Y], axis=1)  

# Save to CSV file
df_combined.to_csv("chronic_kidney_disease.csv", index=False)

In [17]:
# Count missing values in each feature
missing_values =X.isnull().sum()

# Display missing values count
print("\nMissing values in each feature:")
print(missing_values)

Missing values in each feature:
age        9
bp        12
sg        47
al        46
su        49
rbc      152
pc        65
pcc        4
ba         4
bgr       44
bu        19
sc        17
sod       87
pot       88
hemo      52
pcv       71
wbcc     106
rbcc     131
htn        2
dm         2
cad        2
appet      1
pe         1
ane        1
dtype: int64

### Drop rows with missing values in columns where the count of missing data is small enough to be negligible

In [18]:
X = X.dropna(subset=['pcc', 'ba' , 'htn', 'dm' , 'cad' , 'appet', 'pe' , 'ane'])

# Since rows are dropped from X, now we need to drop the corresponding rows from Y
Y = Y.loc[X.index]
print(X.shape)
print(Y.shape)

(393, 24)
(393, 1)

In [19]:
# Count missing values in each feature
missing_values =X.isnull().sum()

# Display missing values count
print("\nMissing values in each feature:")
print(missing_values)

Missing values in each feature:
age        9
bp        11
sg        47
al        46
su        49
rbc      151
pc        64
pcc        0
ba         0
bgr       44
bu        19
sc        17
sod       87
pot       88
hemo      51
pcv       71
wbcc     106
rbcc     131
htn        0
dm         0
cad        0
appet      0
pe         0
ane        0
dtype: int64

### Filling Missing Values with Mean or Mode

In [20]:
# Define the imputation strategies for each column
impute_methods = {
    'su': 'mode', 'wbcc': 'mean', 'age': 'mean', 'rbcc': 'mean', 
    'al': 'mode', 'rbc': 'mode', 'pc': 'mode', 'bgr': 'mean', 
    'pot': 'mean', 'hemo': 'mean', 'pcv': 'mean', 'sod': 'mean', 
    'bp': 'mean', 'bu': 'mean', 'sc': 'mean', 'sg': 'mode'
}

# Handle missing values using the specified methods
for column, method in impute_methods.items():
    if method == 'mean':
        X[column] = X[column].fillna(X[column].mean())
    elif method == 'mode':
        X[column] = X[column].fillna(X[column].mode()[0])

# Display the updated DataFrame
print(X)

      age    bp     sg   al   su     rbc        pc         pcc          ba  \
0    48.0  80.0  1.020  1.0  0.0  normal    normal  notpresent  notpresent
1     7.0  50.0  1.020  4.0  0.0  normal    normal  notpresent  notpresent
2    62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent
3    48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent
4    51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent
..    ...   ...    ...  ...  ...     ...       ...         ...         ...
395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent  notpresent
396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent  notpresent
397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent  notpresent
398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent  notpresent
399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent  notpresent

            bgr  ...  hemo   pcv    wbcc      rbcc  htn   dm  cad  appet   pe  \
0    121.000000  ...  15.4  44.0  7800.0  5.200000  yes  yes   no   good   no
1    148.954155  ...  11.3  38.0  6000.0  4.682443   no   no   no   good   no
2    423.000000  ...   9.6  31.0  7500.0  4.682443   no  yes   no   poor   no
3    117.000000  ...  11.2  32.0  6700.0  3.900000  yes   no   no   poor  yes
4    106.000000  ...  11.6  35.0  7300.0  4.600000   no   no   no   good   no
..          ...  ...   ...   ...     ...       ...  ...  ...  ...    ...  ...
395  140.000000  ...  15.7  47.0  6700.0  4.900000   no   no   no   good   no
396   75.000000  ...  16.5  54.0  7800.0  6.200000   no   no   no   good   no
397  100.000000  ...  15.8  49.0  6600.0  5.400000   no   no   no   good   no
398  114.000000  ...  14.2  51.0  7200.0  5.900000   no   no   no   good   no
399  131.000000  ...  15.8  53.0  6800.0  6.100000   no   no   no   good   no

     ane
0     no
1     no
2    yes
3    yes
4     no
..   ...
395   no
396   no
397   no
398   no
399   no

[393 rows x 24 columns]

In [21]:
# Count missing values in each feature
missing_values =X.isnull().sum()

# Display missing values count
print("\nMissing values in each feature:")
print(missing_values)

Missing values in each feature:
age      0
bp       0
sg       0
al       0
su       0
rbc      0
pc       0
pcc      0
ba       0
bgr      0
bu       0
sc       0
sod      0
pot      0
hemo     0
pcv      0
wbcc     0
rbcc     0
htn      0
dm       0
cad      0
appet    0
pe       0
ane      0
dtype: int64

### Now the data set has no missing values

###  Convert  to binary values

In [36]:
# Ensure the column is converted to strings
Y['class'] = Y['class'].astype(str)

# Remove leading and trailing whitespace
Y['class'] = Y['class'].str.strip()

# Replace unwanted characters
Y['class'] = Y['class'].replace({'ckd\t': 'ckd', 'ckd\n': 'ckd', 'notckd\t': 'notckd', 'notckd\n': 'notckd'})

# Map the cleaned values to binary integers
Y['class'] = Y['class'].map({'ckd': 1, 'notckd': 0})


# Ensure the column is converted to strings
X['dm'] = X['dm'].astype(str)

# Remove leading and trailing whitespace
X['dm'] = X['dm'].str.strip()

# Replace unwanted characterss
X['dm'] = X['dm'].replace({'yes\t': 'yes', 'yes\n': 'yes', 'no\t': 'no', 'no\n': 'no'})

# Map the cleaned values to binary integers
X['dm'] = X['dm'].map({'yes': 1, 'no': 0})

X['htn'] = X['htn'].map({'yes': 1, 'no': 0})
X['cad'] = X['cad'].map({'yes': 1, 'no': 0})
X['pe'] = X['pe'].map({'yes': 1, 'no': 0})
X['appet'] = X['appet'].map({'good': 1, 'poor': 0})
X['ane'] = X['ane'].map({'yes': 1, 'no': 0})
X['rbc'] = X['rbc'].map({'normal': 0, 'abnormal': 1})
X['pc'] = X['pc'].map({'normal': 0, 'abnormal': 1})
X['pcc'] = X['pcc'].map({'notpresent': 0, 'present': 1})
X['ba'] = X['ba'].map({'notpresent': 0, 'present': 1})

In [37]:
# Display data types of all features in the DataFrame
print(X.dtypes)

age      float64
bp       float64
sg       float64
al       float64
su       float64
rbc        int64
pc         int64
pcc        int64
ba         int64
bgr      float64
bu       float64
sc       float64
sod      float64
pot      float64
hemo     float64
pcv      float64
wbcc     float64
rbcc     float64
htn        int64
dm         int64
cad        int64
appet      int64
pe         int64
ane        int64
dtype: object

In [38]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X[['wbcc', 'bgr', 'bp','bu','pcv','sod','hemo']] = scaler.fit_transform(X[['wbcc', 'bgr' ,'bp','bu','pcv','sod','hemo']])

In [39]:
print("Shape of X:", X.shape)
print("Shape of Y:", Y.shape)

Shape of X: (393, 24)
Shape of Y: (393, 1)

In [40]:
# Display data types of all features in the DataFrame
print(X.dtypes)

age      float64
bp       float64
sg       float64
al       float64
su       float64
rbc        int64
pc         int64
pcc        int64
ba         int64
bgr      float64
bu       float64
sc       float64
sod      float64
pot      float64
hemo     float64
pcv      float64
wbcc     float64
rbcc     float64
htn        int64
dm         int64
cad        int64
appet      int64
pe         int64
ane        int64
dtype: object

In [41]:
# Display data types of all features in the DataFrame
print(Y.dtypes)

class    int64
dtype: object

### Training the model

In [42]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [43]:
# Combine the updated X (features) and Y (target) back into a single DataFrame
df_combined_updated = pd.concat([X, Y], axis=1)

# Save the combined DataFrame to a CSV file
df_combined_updated.to_csv("chronic_kidney_disease_updated.csv", index=False)

In [44]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.metrics import accuracy_score

In [45]:
# Load the dataset
df = pd.read_csv('chronic_kidney_disease_updated.csv')

In [46]:
# Encoding categorical variables
label_encoder = LabelEncoder()
df['class'] = label_encoder.fit_transform(df['class'])  # Encode the target variable

# Split the dataset into features (X) and target (y)
X = df.drop('class', axis=1)
y = df['class']

In [47]:
#Split the data set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

### Apply Ensemble Methods

### Random Forest Classifier

In [50]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
print("Random Forest Accuracy: ", accuracy_score(y_test, rf_pred))

Random Forest Accuracy:  0.9915254237288136

### Gradient Boosting Classifier

In [51]:
gb_model = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_model.fit(X_train, y_train)
gb_pred = gb_model.predict(X_test)
print("Gradient Boosting Accuracy: ", accuracy_score(y_test, gb_pred))

Gradient Boosting Accuracy:  0.9830508474576272

### Voting Classifier

In [52]:
voting_model = VotingClassifier(estimators=[('rf', rf_model), ('gb', gb_model)], voting='hard')
voting_model.fit(X_train, y_train)
voting_pred = voting_model.predict(X_test)
print("Voting Classifier Accuracy: ", accuracy_score(y_test, voting_pred))

Voting Classifier Accuracy:  0.9830508474576272

In [59]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
import numpy as np

# Build individual models
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
gb_model = GradientBoostingClassifier(n_estimators=100, random_state=42)

# Build the ensemble model
voting_model = VotingClassifier(estimators=[('rf', rf_model), ('gb', gb_model)], voting='hard')

# Train all models
print("Training models...")
models = [rf_model, gb_model, voting_model]
for model in models:
    model.fit(X_train, y_train)

# Evaluate models
print("\nEvaluating models...")
for model in models:
    y_pred = model.predict(X_test)
    print(f"\nModel: {model.__class__.__name__}")
    print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
    print(classification_report(y_test, y_pred))

# Simulate real-time predictions
print("\nSimulating Real-Time Predictions...")
for i in range(5):  # You can change this number to simulate more samples
    print(f"Predicting Sample {i + 1}...")
    
    # Predict with individual models
    rf_pred = rf_model.predict(X_test.iloc[i:i+1])[0]
    gb_pred = gb_model.predict(X_test.iloc[i:i+1])[0]
    voting_pred = voting_model.predict(X_test.iloc[i:i+1])[0]


    print(f"Model RandomForestClassifier: {rf_pred}")
    print(f"Model GradientBoostingClassifier: {gb_pred}")
    print(f"Model VotingClassifier: {voting_pred}")

    # Ensemble Final Prediction (majority voting)
    ensemble_pred = np.round(np.mean([rf_pred, gb_pred, voting_pred]))
    print(f"Ensemble Final Prediction: {int(ensemble_pred)}\n")

Training models...

Evaluating models...

Model: RandomForestClassifier
Accuracy: 0.9915254237288136
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        40
           1       1.00      0.99      0.99        78

    accuracy                           0.99       118
   macro avg       0.99      0.99      0.99       118
weighted avg       0.99      0.99      0.99       118


Model: GradientBoostingClassifier
Accuracy: 0.9830508474576272
              precision    recall  f1-score   support

           0       0.95      1.00      0.98        40
           1       1.00      0.97      0.99        78

    accuracy                           0.98       118
   macro avg       0.98      0.99      0.98       118
weighted avg       0.98      0.98      0.98       118


Model: VotingClassifier
Accuracy: 0.9830508474576272
              precision    recall  f1-score   support

           0       0.95      1.00      0.98        40
           1       1.00      0.97      0.99        78

    accuracy                           0.98       118
   macro avg       0.98      0.99      0.98       118
weighted avg       0.98      0.98      0.98       118


Simulating Real-Time Predictions...
Predicting Sample 1...
Model RandomForestClassifier: 1
Model GradientBoostingClassifier: 1
Model VotingClassifier: 1
Ensemble Final Prediction: 1

Predicting Sample 2...
Model RandomForestClassifier: 0
Model GradientBoostingClassifier: 0
Model VotingClassifier: 0
Ensemble Final Prediction: 0

Predicting Sample 3...
Model RandomForestClassifier: 1
Model GradientBoostingClassifier: 1
Model VotingClassifier: 1
Ensemble Final Prediction: 1

Predicting Sample 4...
Model RandomForestClassifier: 1
Model GradientBoostingClassifier: 1
Model VotingClassifier: 1
Ensemble Final Prediction: 1

Predicting Sample 5...
Model RandomForestClassifier: 0
Model GradientBoostingClassifier: 0
Model VotingClassifier: 0
Ensemble Final Prediction: 0

In [61]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.model_selection import train_test_split
import pickle

# Assuming X and y are your features and labels for the kidney dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create individual models
rf_model = RandomForestClassifier()
gb_model = GradientBoostingClassifier()

# Create an ensemble model
ensemble_model = VotingClassifier(estimators=[('rf', rf_model), ('gb', gb_model)], voting='hard')

# Train the ensemble model
ensemble_model.fit(X_train, y_train)

# Save the model using pickle
with open('predictor.pkl', 'wb') as file:
    pickle.dump(ensemble_model, file)

# Optional: Check accuracy of the model
print(f"Ensemble Model Accuracy: {ensemble_model.score(X_test, y_test)}")

Ensemble Model Accuracy: 0.9830508474576272

In [62]:
print("Shape of X:", X.shape)
print("Shape of Y:", Y.shape)

Shape of X: (393, 24)
Shape of Y: (393, 1)